server:
  port: 8050
  context-path: /uaa
security:
  oauth2:
    resource:
      filter-order: 3
spring:
  application:
    name: auth-security
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/