server:
  port: 8762
management:
  port: 8763
  security:
    enabled: false
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zuul_route?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  application:
    name: hello-world
mybatis:
  mapperLocations:
    - classpath*:/mapper/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/