#服务器配置
server:
  #端口
  port: 8020

#spring配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_server?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  application:
    name: auth-server
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
mybatis:
  mapperLocations:
    - classpath*:/mapper/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true
#安全配置
security:
  #oauth2配置
  oauth2:
    resource:
      filter-order: 3

#服务器发现注册配置
eureka:
  client:
    serviceUrl:
      #配置服务中心(可配置多个,用逗号隔开)
      defaultZone: http://peer1:8000/eureka/
